"""initial schema

Revision ID: 8216403616b0
Revises: 
Create Date: 2026-09-23 12:38:19.207247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8216403616b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'name', name='uq_food_category_name')
    )
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_item_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_item_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('food_exclusion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_item_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'food_item_id', name='uq_excl_user_item')
    )
    with op.batch_alter_table('food_exclusion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_exclusion_food_item_id'), ['food_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_exclusion_user_id'), ['user_id'], unique=False)

    op.create_table('food_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_item_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    with op.batch_alter_table('food_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_image_food_item_id'), ['food_item_id'], unique=False)

    op.create_table('preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_item_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('rated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'food_item_id', name='uq_pref_user_item')
    )
    with op.batch_alter_table('preference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preference_food_item_id'), ['food_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_preference_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preference_user_id'))
        batch_op.drop_index(batch_op.f('ix_preference_food_item_id'))

    op.drop_table('preference')
    with op.batch_alter_table('food_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_image_food_item_id'))

    op.drop_table('food_image')
    with op.batch_alter_table('food_exclusion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_exclusion_user_id'))
        batch_op.drop_index(batch_op.f('ix_food_exclusion_food_item_id'))

    op.drop_table('food_exclusion')
    op.drop_table('followers')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('food_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_item_name'))
        batch_op.drop_index(batch_op.f('ix_food_item_category'))

    op.drop_table('food_item')
    # ### end Alembic commands ###
